# Generated by Django 5.2.17 on 2026-09-13 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_creativeproject_portfolioitem_delete_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
