# Generated by Django 5.2.17 on 2026-09-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_creativeproject_portfolioitem_delete_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image_url',
            field=models.CharField(blank=True, help_text='Imgur link or /static/img/ path', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
