# Generated by Django 5.2.17 on 2026-09-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_portfolioitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
