# Generated by Django 5.2.17 on 2026-09-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_portfolioitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image_url',
            field=models.CharField(blank=True, help_text='Imgur link or /static/img/ path', max_length=500, null=True),
        ),
    ]
